# Generated by Django 2.1.7 on 2019-03-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0003_auto_20190307_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
