# Generated by Django 2.1.7 on 2019-03-11 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediaportalapp', '0004_auto_20190309_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_reaction',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
